server:
  port: 8888
spring:
  application:
    name: configServer
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations: file:${user.home}/.springCloudConfig/{label}/{application}/{profile}